pfs_client.lo: /home/jingchun.zhang/svn/sys_dev/56pfs/code/php_client/pfs_client.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/jingchun.zhang/svn/sys_dev/56pfs/code/php_client $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/jingchun.zhang/svn/sys_dev/56pfs/code/php_client/pfs_client.c -o pfs_client.lo 
$(phplibdir)/pfs_client.la: ./pfs_client.la
	$(LIBTOOL) --mode=install cp ./pfs_client.la $(phplibdir)

./pfs_client.la: $(shared_objects_pfs_client) $(PFS_CLIENT_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_pfs_client) $(PFS_CLIENT_SHARED_LIBADD)

